
{{ if hasKey .Values.env }}
  {{ fail "The Value env has been renamed and moved to askargus.configEnv. Refer to https://www.askargus.ai/docs/local/helm_chart#migrate for more information" }}
{{ end }}